### ISSUE TITLE
Fix Host Function Example in the Readme 

### ISSUE THREAD

**Issue by neuronicnobody** [extism/zig-sdk#6]
The KV store code example in the Readme that is used to demonstrate Extism Host Functions requires the following correction(s):

- [x] Add correct type conversions between little-endian bytes and unsigned integers when writing / reading values from the KV store and returning from the Host Function to the caller (ie. Plugin)
- [x] The kv_read host function does not correctly set the return value

**Comment by nilslice** [comment]
Complete in https://github.com/extism/zig-sdk/commit/c919359a04fa84b40f251b8209cd2c3f4c2f168f
